repos:
  - repo: local
    hooks:
      - id: trufflehog-check
        name: trufflehog check
        description: Detect secrets in your data.
        entry: trufflehog git file://. --since-commit HEAD --fail
        language: system
        pass_filenames: false
        stages: ["pre-commit"]
